services:
   mineru2.5-pro:
    image: vllm/vllm-openai:latest
    container_name: mineru2.5-pro
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
      - CUDA_VISIBLE_DEVICES=1
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8001:8000" # host port 8001 map tới container port 8000
    ipc: host
    command: >
      opendatalab/MinerU2.5-Pro-2604-1.2B --max-model-len 512 --max-num-seqs 1 --gpu-memory-utilization 0.5 --dtype float16
